### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by rugk** [oversecio/oversec_crypto#23]
Currently one does not know what the software is about when reading the Readme. So please improve it.
Preferably add some screenshots.

**Comment by oversecio** [comment]
Thanks, good point, will do!

**Comment by oversecio** [comment]
done (for now)

**Comment by rugk** [comment]
Maybe a bit less bold/heading-like text would have been nice. (You're not in an ad campaign here :wink: ), but yeah, thanks for the improvement. It is much more informative than before.
